# Generated by Django 5.0.6 on 2024-06-07 06:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_task_submitted_time_task_task_given_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('Entry_time', models.TimeField()),
                ('Exit_time', models.TimeField()),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Attendence', to='api.userprofile')),
            ],
        ),
    ]
